version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - sphinx-apidoc -o ./docs/source ./geotils
      - dir
    post_build:
      - ./docs/make.bat html

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
